#include "device_code.h"
#include "iBeacon_advertising.h"
#include "wifi_manager.h"
#include "mqtt_manager.h"
#include "ble_scanning.h"
#include "mifare_reader.h"
#include "notif.h"
#include "FS_config.h"
#include <SPI.h>
